### ISSUE TITLE
Pass options to kernel?

### ISSUE THREAD

**Issue by Red5d** [danderson/pixiecore#2]
Is it possible to pass options to the kernel with this? I'd like to be able to specify an nfsroot option for booting with a remote NFS root filesystem.

**Comment by moul** [comment]
Based on the example on the `README.md`,

I think that you are looking for the `--cmdline` option, i.e: `pixiecore -kernel coreos_production_pxe.vmlinuz -initrd coreos_production_pxe_image.cpio.gz --cmdline coreos.autologin`

**Comment by danderson** [comment]
Correct, -cmdline "nfsroot=....." will pass that option, if you're booting in static mode. Likewise, the remote API lets you specify the kernel commandline.
