### ISSUE TITLE
[Question] is everything in the tftp folder shared, or just the pxelinux stuff?

### ISSUE THREAD

**Issue by faddat** [danderson/pixiecore#20]
I ask, because I'd like to stash the preseed.cfg for debian / ubuntu in there, instead of having to download them from outside, and either serve locally or from there.  

Thanks!

-Jake

Ps:  Question is:  If I put a preseed.cfg in there, will it also be served so that I can load it somewhat akin to:

```
auto=true locale=en_US console-setup/charmap=UTF-8 console-keymaps-at/keymap=jp console-setup/layoutcode=jp console-setup/ask_detect=false pkgsel/language-pack-patterns=pkgsel/install-language-support=false interface=eth0 hostname=<hostname> domain=<your domain> url=tftp://<TFTP Server IP>/debian/7.4/preseed.cfg DEBCONF_DEBUG=5 initrd=debian/7.4/amd64/initrd.gz quiet --
```

**Comment by danderson** [comment]
The tftp directory is just a Go package that implements a TFTP server. Pixiecore doesn't serve any directory from disk, it only serves the given kernel and initrd (if running in static mode - in API mode, the API server can tell it to serve other files as well).

It would be nice to add support for serving specific static files in static mode - however, they should be served from the HTTP server, not the TFTP server. The TFTP server is used only to send PXELinux to the booting machine, after that everything is served over HTTP.

**Comment by faddat** [comment]
Gotcha, thank you for clearing that up for me!  

Usually when running pixiecore, I start a separate http server.  if you look at my fork, you'll see a folder /httpsupplements which is where I have been stashing the files to be served via http so that (for example) a cloud-config can be loaded.  I usually use goserve https://github.com/johnsto/goserve to do that because it's fast and simple.  I am still working on the structure of my autoinstallers folder.  Once it is done, I will send a PR for it, if you'd like that to join pixiecore, and if not, I'll take pixiecore out of my fork and just have a freestanding repo of scripts that use pixiecore.
