### ISSUE TITLE
Support clients that don't send DHCP option 97 (Support bad intel cards)

### ISSUE THREAD

**Issue by guilhem** [danderson/pixiecore#21]
We just received some new server with this card:
```
03:00.0 Ethernet controller: Intel Corporation Ethernet Connection X552/X557-AT 10GBASE-T
```
PXE bios is 2015 dated.

here is _exactly_ all the check I have to remove to make it working:
https://github.com/guilhem/pixiecore/commit/232b5aa35cb87b99fca32bd4d8c81590263943d3

None of them is optionnal :disappointed: 

What do you think about it?

**Comment by danderson** [comment]
Hmm, that's bizarre. Based on the checks you removed, naively it looks like this machine doesn't implement PXE *or* DHCP correctly, because it's missing required fields for both. The other possibility is that it's speaking some other protocol that is not "true" PXE, or that Pixiecore is confusing the client.

Can you get me a packet capture of the machine attempting to netboot (a) with your patch and (b) with a vanilla pixiecore? If you have wireshark the capture filter "port 67 or port 68 or tftp" is what I need (feel free to add a MAC address filter as well, the above filter is what I use at home to debug). I'd like to see the raw packets to try and figure out what this card is trying to do.

If you feel like it, could you also try to set up dnsmasq in ProxyDHCP+TFTP mode, and if it successfully boots the machine (at least up to downloading a file from TFTP, no need to set up the full boot sequence) ? If it does, can you give me the same packet capture with that setup? I can give you a dnsmasq config for this in a few hours when I'm back home.

**Comment by danderson** [comment]
Ah, there's another possibility: DHCP has an option called "Option overload", which reuses uninteresting fields of the legacy BOOTP header to store DHCP options. Pixiecore doesn't currently implement this option, so if your PXE ROM is using it, Pixiecore is going to miss ~all the DHCP options in the request, and incorrectly conclude that the request is borked.

I'm working on better DHCP parsing support right now, but to confirm that this is your problem, I really need a packet capture of the NIC's initial DHCPDISCOVER request.

**Comment by guilhem** [comment]
@danderson Here is a dump with [with-fix.zip](https://github.com/danderson/pixiecore/files/144381/with-fix.zip)

For information:
* 172.16.1.1 is dhcp (using [netcore](https://github.com/dustywilson/netcore) (who is working fine))
* 172.16.1.3 is pixicore
* 172.17.0.5 server to launch

**Comment by guilhem** [comment]
Without patch I don't have any answer from pixiecore and this log:
```
Feb 24 15:38:07 srv1 docker[19371]: 2016/02/24 15:38:07 [ProxyDHCP] ParseDHCP: 0c:c4:7a:c3:40:bf is not a PXE client
Feb 24 15:38:11 srv1 docker[19371]: 2016/02/24 15:38:11 [ProxyDHCP] ParseDHCP: 0c:c4:7a:c3:40:bf is not a PXE client
Feb 24 15:38:15 srv1 docker[19371]: 2016/02/24 15:38:15 [ProxyDHCP] ParseDHCP: 0c:c4:7a:c3:40:bf is not a PXE client
Feb 24 15:38:19 srv1 docker[19371]: 2016/02/24 15:38:19 [ProxyDHCP] ParseDHCP: 0c:c4:7a:c3:40:bf is not a PXE client
Feb 24 15:38:23 srv1 docker[19371]: 2016/02/24 15:38:23 [ProxyDHCP] ParseDHCP: 0c:c4:7a:c3:40:bf is not a PXE client
Feb 24 15:38:27 srv1 docker[19371]: 2016/02/24 15:38:27 [ProxyDHCP] ParseDHCP: 0c:c4:7a:c3:40:bf is not a PXE client
Feb 24 15:38:31 srv1 docker[19371]: 2016/02/24 15:38:31 [ProxyDHCP] ParseDHCP: 0c:c4:7a:c3:40:bf is not a PXE client
Feb 24 15:38:35 srv1 docker[19371]: 2016/02/24 15:38:35 [ProxyDHCP] ParseDHCP: 0c:c4:7a:c3:40:bf is not a PXE client
```

**Comment by danderson** [comment]
Okay, first of all, I screwed up the pcap filter. Could you run it again with "port 67 or port 68 or port 4011 or tftp" ? The messages to the PXE server are missing :(

Looking at the DHCP packets, they look fine except that the GUID is missing. The PXE spec technically requires the GUID identifier, but in practice we could relax that check and detect PXE packets some other way (e.g. look for the client architecture options, or the magic requested options 128-135).

It's more interesting that the DHCP message type check makes the boot fail, because the client and pixiecore are sending the correct message types. One possibility is that the client wants to get a ProxyDHCP response for the DHCPREQUEST as well as the original DHCPDISCOVER... Again, not compliant with the spec, but it shouldn't hurt to send anyway.

Could you redo the capture (with your patch) that includes port 4011 packets, so I can look at what the PXE request?

**Comment by guilhem** [comment]
@danderson thanks for your answer, I'm doing this right now.

It would be great to see a "great" go dhcp library going out from this :)

**Comment by guilhem** [comment]
@danderson Done: [with-4011.zip](https://github.com/danderson/pixiecore/files/144913/with-4011.zip)

**Comment by danderson** [comment]
Thanks for the pcaps!

The requests to port 4011 are also missing the GUID, so that will definitely have to become optional.

The boot server type check looks correct: the packets contain the correct boot menu entry option, so that check ("sif ret.BootType == nil") hould not be failing.

Based on the pcap, I think some of the checks you removed can remain, as long as we tweak the others to convince your PXE ROM to talk to us. I'll construct a quick patch to test that, stand by.

**Comment by danderson** [comment]
Could you pull and build the "intel-hacks" branch, and try that? It has a few extra flags to enable/disable specific behavior. Could you try the following options in order, until one of them successfully boots your machine?

1. No extra flags, just use whatever you're already using (this just disables GUID checking)
2. With -reply-on-dhcprequest (reply on DHCPREQUEST as well as DHCPDISCOVER)
3. With -reply-on-dhcprequest and -ignore-missing-boottype (disables the PXE boot type check, but still puts a boot type in the response)
4. With -reply-on-dhcprequest, -ignore-missing-boottype, and -no-boottype-in-reply (does not put boot type in reply, which is *really* out of spec).

Based on the pcaps I've seen so far, my guess is that 1 or 2 will successfully boot. If 1 and 2 both fail, could you get me a pcap of the attempt with option 2? I want to see where the transaction dies.

**Comment by danderson** [comment]
Oh, and one more note: with option 1 and -debug, pixiecore will still complain that some packets are not DHCPDISCOVER. This is normal for a ProxyDHCP server, it should only respond to DHCPDISCOVER. Pixiecore is just saying "FYI, I got a DHCPREQUEST packet, and I'm ignoring it".

**Comment by guilhem** [comment]
option 1:
```
$ sudo /tmp/pixiecore -api http://169.254.255.254:7494/api -debug=true 
2016/02/24 17:11:38 Starting Pixiecore in API mode, with server http://169.254.255.254:7494/api
2016/02/24 17:11:38 [HTTP] Listening on :70
2016/02/24 17:11:38 [PXE] Listening on :4011
2016/02/24 17:11:38 [TFTP] Listening on 0.0.0.0:69
2016/02/24 17:11:38 [ProxyDHCP] Listening on :67
2016/02/24 17:15:01 [ProxyDHCP] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:15:01 [ProxyDHCP] Offering to boot 0c:c4:7a:c3:40:bf (via 172.16.1.1)
2016/02/24 17:15:05 [ProxyDHCP] ParseDHCP: packet from 0c:c4:7a:c3:40:bf is not a DHCPDISCOVER
2016/02/24 17:15:05 [PXE] Parsing PXE vendor extensions
2016/02/24 17:15:05 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:15:05 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:15:05 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
2016/02/24 17:15:06 [PXE] Parsing PXE vendor extensions
2016/02/24 17:15:06 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:15:06 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:15:06 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
2016/02/24 17:15:08 [PXE] Parsing PXE vendor extensions
2016/02/24 17:15:08 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:15:08 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:15:08 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
2016/02/24 17:15:11 [PXE] Parsing PXE vendor extensions
2016/02/24 17:15:11 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:15:11 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:15:11 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
```

option 2:
```
$ sudo /tmp/pixiecore -api http://169.254.255.254:7494/api -debug=true -reply-on-dhcprequest
2016/02/24 17:17:03 Starting Pixiecore in API mode, with server http://169.254.255.254:7494/api
2016/02/24 17:17:03 [HTTP] Listening on :70
2016/02/24 17:17:03 [PXE] Listening on :4011
2016/02/24 17:17:03 [ProxyDHCP] Listening on :67
2016/02/24 17:17:03 [TFTP] Listening on 0.0.0.0:69
2016/02/24 17:17:36 [ProxyDHCP] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:17:36 [ProxyDHCP] Offering to boot 0c:c4:7a:c3:40:bf (via 172.16.1.1)
2016/02/24 17:17:40 [ProxyDHCP] ParseDHCP: packet from 0c:c4:7a:c3:40:bf is not a DHCPDISCOVER
2016/02/24 17:17:40 [PXE] Parsing PXE vendor extensions
2016/02/24 17:17:40 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:17:40 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:17:40 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
2016/02/24 17:17:41 [PXE] Parsing PXE vendor extensions
2016/02/24 17:17:41 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:17:41 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:17:41 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
2016/02/24 17:17:43 [PXE] Parsing PXE vendor extensions
2016/02/24 17:17:43 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:17:43 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:17:43 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
2016/02/24 17:17:46 [PXE] Parsing PXE vendor extensions
2016/02/24 17:17:46 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:17:46 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:17:46 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
```

option 3:
```
$ sudo /tmp/pixiecore -api http://169.254.255.254:7494/api -debug=true -reply-on-dhcprequest -ignore-missing-boottype
2016/02/24 17:18:40 Starting Pixiecore in API mode, with server http://169.254.255.254:7494/api
2016/02/24 17:18:40 [HTTP] Listening on :70
2016/02/24 17:18:40 [ProxyDHCP] Listening on :67
2016/02/24 17:18:40 [TFTP] Listening on 0.0.0.0:69
2016/02/24 17:18:40 [PXE] Listening on :4011
2016/02/24 17:19:32 [ProxyDHCP] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:19:32 [ProxyDHCP] Offering to boot 0c:c4:7a:c3:40:bf (via 172.16.1.1)
2016/02/24 17:19:36 [ProxyDHCP] ParseDHCP: packet from 0c:c4:7a:c3:40:bf is not a DHCPDISCOVER
2016/02/24 17:19:36 [PXE] Parsing PXE vendor extensions
2016/02/24 17:19:36 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:19:36 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:19:36 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
2016/02/24 17:19:37 [PXE] Parsing PXE vendor extensions
2016/02/24 17:19:37 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:19:37 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:19:37 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
2016/02/24 17:19:39 [PXE] Parsing PXE vendor extensions
2016/02/24 17:19:39 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:19:39 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:19:39 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
2016/02/24 17:19:42 [PXE] Parsing PXE vendor extensions
2016/02/24 17:19:42 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:19:42 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:19:42 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
```

option 4 WORKS:
```
$ sudo /tmp/pixiecore -api http://169.254.255.254:7494/api -debug=true -reply-on-dhcprequest -ignore-missing-boottype -no-boottype-in-reply
2016/02/24 17:20:03 Starting Pixiecore in API mode, with server http://169.254.255.254:7494/api
2016/02/24 17:20:03 [HTTP] Listening on :70
2016/02/24 17:20:03 [PXE] Listening on :4011
2016/02/24 17:20:03 [ProxyDHCP] Listening on :67
2016/02/24 17:20:03 [TFTP] Listening on 0.0.0.0:69
2016/02/24 17:20:35 [ProxyDHCP] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:20:35 [ProxyDHCP] Offering to boot 0c:c4:7a:c3:40:bf (via 172.16.1.1)
2016/02/24 17:20:39 [ProxyDHCP] ParseDHCP: packet from 0c:c4:7a:c3:40:bf is not a DHCPDISCOVER
2016/02/24 17:20:39 [PXE] Parsing PXE vendor extensions
2016/02/24 17:20:39 [PXE] PXE option 71 = []byte{0x80, 0x0, 0x0, 0x0}
2016/02/24 17:20:39 [PXE] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:20:39 [PXE] Chainloading 0c:c4:7a:c3:40:bf (172.17.0.5) to pxelinux (via 172.16.1.1)
2016/02/24 17:20:40 [TFTP] Transfer to 172.17.0.5:2070 failed: client aborted transfer ("TFTP Aborted")
2016/02/24 17:20:40 [TFTP] Sent "boot" to 172.17.0.5:2071
2016/02/24 17:20:40 [HTTP] Starting send of ldlinux.c32 to 172.17.0.5:49153 (122308 bytes)
2016/02/24 17:20:40 [HTTP] Sent ldlinux.c32 to 172.17.0.5:49153 (122308 bytes)
2016/02/24 17:20:40 [HTTP] Sent pxelinux config to 0c:c4:7a:c3:40:bf (172.17.0.5:49154)
2016/02/24 17:20:41 [HTTP] Sent http://beta.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz to 172.17.0.5:49155 (31520064 bytes)
2016/02/24 17:20:49 [HTTP] Sent https://s3-eu-west-1.amazonaws.com/[....] to 172.17.0.5:49156 (204122291 bytes)
2016/02/24 17:21:07 [ProxyDHCP] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:21:07 [ProxyDHCP] Offering to boot 0c:c4:7a:c3:40:bf (via 172.16.1.1)
2016/02/24 17:21:07 [ProxyDHCP] ParseDHCP: packet from 0c:c4:7a:c3:40:bf is not a DHCPDISCOVER
2016/02/24 17:21:08 [HTTP] Sent http://hostlocal.io:7494/api/v1/static/cloud-config-worker.yml to 172.17.0.5:47228 (6263 bytes)
2016/02/24 17:21:08 [ProxyDHCP] HACK: GUID is missing, going to respond without a GUID
2016/02/24 17:21:08 [ProxyDHCP] Offering to boot 0c:c4:7a:c3:40:bf (via 172.16.1.1)
2016/02/24 17:21:08 [ProxyDHCP] ParseDHCP: packet from 0c:c4:7a:c3:40:bf is not a DHCPDISCOVER
```

**Comment by guilhem** [comment]
Option 5: `pixiecore -api http://169.254.255.254:7494/api -debug=true -no-boottype-in-reply`
Works ;)

**Comment by danderson** [comment]
... Wow, I should not be allowed to write code before coffee. I got the condition for -no-boottype-in-reply backwards :(

Okay, so with the GUIDs optional, and my no-boottype mistake undone (option 5), your system can boot. Great! I'll have a permanent fix submitted in a few hours (I'm going to be afk for a bit).

If you have a way to contact the vendor of the NIC/motherboard, I encourage you to file a bug report with them as well to fix their firmware (you can reference ftp://download.intel.com/design/archives/wfm/downloads/pxespec.pdf section 2.3 note 1, "The client must have a UUID and must report it in tag 97 and 61."). In this case, I can make pixiecore interoperate without breaking conformant clients, but it's a good idea to encourage firmware vendors to follow the spec :).

**Comment by danderson** [comment]
@guilhem Can you test the master branch again and confirm that it can boot your machines?

**Comment by guilhem** [comment]
@danderson seems to work fine here :)
