### ISSUE TITLE
Support single binaries like memtest86+

### ISSUE THREAD

**Issue by lae** [danderson/pixiecore#25]
Currently I'm unable to serve the memtest binary to clients because an initrd is required, which then adds an argument for initrd and results in a `Booting kernel failed: Invalid argument ` error during PXE boot attempts.

Can we make the initrd argument optional?

**Comment by danderson** [comment]
Sure, sounds reasonable. I'm actually not sure if memtest86 will be bootable from pxelinux anyway, but making the initrd optional is definitely reasonable.

**Comment by danderson** [comment]
Tested on my local test rig, I can boot memtest86 with `sudo pixiecore -kernel memtest86+-5.01.bin`.

**Comment by lae** [comment]
Thanks!
