### ISSUE TITLE
ACIs - App Container Images

### ISSUE THREAD

**Issue by urzds** [danderson/pixiecore#28]
It would be great to have ACIs (App Container Images) for Pixiecore.

See for example the CoreOS dnsmasq build instructions: https://github.com/coreos/coreos-baremetal/tree/master/contrib/dnsmasq#aci In addition to scripts to build ACIs oneself, there is work underway to publish dnsmasq images using some registry: coreos/coreos-baremetal#69

**Comment by s7726** [comment]
I this:
`sudo docker run -v .:/image --net=host danderson/pixiecore -kernel /image/coreos_production_pxe.vmlinuz -initrd /image/coreos_production_pxe_image.cpio.gz`

not what your asking for?

**Comment by urzds** [comment]
Afaik Docker Engine / Docker Hub does not yet support ACIs / OCI bundles. I think that what the Docker Engine downloads in the commandline you quoted is a Docker Image.

**Comment by s7726** [comment]
Yes I believe that is correct. I guess I'm not clear I the difference. Do
you have a good link with more info?

**Comment by danderson** [comment]
To the best of my knowledge, there are currently no image hosts that support building/serving ACIs with github integration (so that I don't have to remember to rebuild ACIs all the time). Do you know of any such hosts?

**Comment by urzds** [comment]
@danderson No, I don't.

@s7726 An overview of how OCI "bundles" and ACIs intersect is given here: https://coreos.com/blog/making-sense-of-standards.html

**Comment by dghubble** [comment]
@danderson Quay.io does not yet support pushing ACIs or host the ACI's directly. If you take a look at the page source for https://coreos.com, you'll see we're using the [ACI discovery metadata](https://github.com/appc/spec/blob/master/spec/discovery.md) to point to Github releases and signatures of ACI's for `etcd` and `bootcfg`.

```
<meta name="ac-discovery" content="coreos.com/etcd https://github.com/coreos/etcd/releases/download/{version}/etcd-{version}-{os}-{arch}.{ext}">
<meta name="ac-discovery-pubkeys" content="coreos.com/etcd https://coreos.com/dist/pubkeys/aci-pubkeys.gpg">
<meta name="ac-discovery" content="coreos.com/bootcfg https://github.com/coreos/coreos-baremetal/releases/download/{version}/bootcfg-{version}-{os}-{arch}.{ext}">
<meta name="ac-discovery-pubkeys" content="coreos.com/bootcfg https://coreos.com/dist/pubkeys/app-signing-pubkey.gpg">
```

So key trust and fetching works like this:

    sudo rkt trust --prefix coreos.com/bootcfg
    sudo rkt fetch coreos.com/bootcfg:v0.2.0

I might write something up about using a personal domain and keys for something like this if it would be helpful?

**Comment by danderson** [comment]
Fascinating! Yes, that would be very helpful, as I'm in the middle of setting up a custom domain for various packages and binaries, including Pixiecore.

**Comment by danderson** [comment]
Moving issue to: https://github.com/google/netboot/issues/5
