### ISSUE TITLE
Note about TinyCoreLinux

### ISSUE THREAD

**Issue by rgl** [danderson/pixiecore#31]
On the README you are downloading the files:

> http://tinycorelinux.net/6.x/x86/release/distribution_files/{vmlinuz64,modules64.gz,core.gz,rootfs.gz}

But you do not actually need all of them. `vmlinuz64` and `core.gz` (this is actually `rootfs` and `modules64` merged together) are enough.

You can see it for yourself with:

```
zcat rootfs.gz | cpio --list --numeric-uid-gid | sort > rootfs.txt
zcat core.gz | cpio --list --numeric-uid-gid | sort > core.txt
diff -u rootfs.txt core.txt
```

So maybe its better to reword the readme. and maybe also update it to use TCL 7.x.

**Comment by danderson** [comment]
Ah, thanks, I didn't know that core.gz was the combination of the two. I'll switch to using rootfs and modules64 (I want to demonstrate the ability to pass multiple initrds in that example), and update to TCL 7. Thanks for the report!
