### ISSUE TITLE
Support serving additional static files in static mode

### ISSUE THREAD

**Issue by gherlein** [danderson/pixiecore#33]
Love this project!  Am trying to figure out how to use it for automated installs.  How do I pass the inst.ks=<> line and tell pixiecore about the kickstarter file?

**Comment by gherlein** [comment]
figured out the first part:  --cmdline "inst-repo=$(REPO_URL) ks=$(KS_URL)"

But, is there a way to get pixiecore to serve those files directly?

**Comment by danderson** [comment]
Currently, there's no good way to serve additional static files when using Pixiecore in static mode, like you are. You could switch to API mode and implement a server that does what you want, but that's obviously more work :(.

Mind if I convert this bug into a feature request to support file serving in static mode?

**Comment by gherlein** [comment]
Of course, that's fine.  :)

**Comment by danderson** [comment]
I've implemented this in my v2 of Pixiecore. You can find it at https://github.com/google/netboot/tree/master/pixiecore .

Specifically: --cmdline 'foo={{ ID "./bar" }}' means "transform this into a URL that serves the contents of ./bar.
