### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hunter** [danderson/pixiecore#4]
We're really liking what you've done with pixiecore and plan to use it for some baremetal CoreOS deployments. One question we have is, do you have any plans for additional features?

Power management and cloud-init are a few things would be useful for us. Happy to contribute code but would like to get an idea of the direction you'd like to take the project.

**Comment by danderson** [comment]
Thanks for the interest! I don't have any specific plans for more features right now, but I'm happy to accept ideas and code. The only guiding principle I have is that I'd like Pixiecore to stay relatively focused on booting machines, and push anything else out to external systems (e.g. pixiecore doesn't decide _what_ to boot, it delegates that via the boot API - it focuses only on executing the boot).

Could you elaborate on what kind of power management you need? At a first glance, it seems a bit out of scope for pixiecore, and would introduce additional infrastructure complexity (e.g. if you mean wake-on-lan, pixiecore now has to expose its own API, figure out authentication for that API, ...). I'm definitely not opposed to it, I'm just curious what you need specifically, and how to elegantly build that into pixiecore.

Cloud init support is fairly CoreOS-specific, and I'd like to keep pixiecore generic if possible. Are you using Pixiecore in API mode? If so, I have a vague plan that might work for you, but again I'd need to know more about your use case.

**Comment by hunter** [comment]
What we've been considering for a while is that there is no decent tool to manage baremetal in a similar way to VMs - API driven (ideally with focus on modern container OSes). A rack of baremetal that can be powered on with IPMI, PXE booted and configured by a cloud-config. That serves as a framework for use in other tools (terraform, docker-machine, Kubernetes, etc).

There are things out there like MAAS, cobbler/foreman, crowbar and parts of Openstack that do something similar but are heavyweight and/or have a bias towards certain OSes.

Agreed about keeping focused, these things may be better built as an external set of tools (with a unifying API). I was really just seeing which direction you were planning to take the project.

**Comment by faddat** [comment]
@hunter 

Me too!  Basically by using pixiecore, I can make my cheap metal dynamic, and I'm having a blast doing it.  I am just getting around to the whole API part now, and I'm curious how you'll be interacting with it.  Thus far I haven't set up any mac address based granularity, so I am using pixiecore mostly as a way to install the same OS onto the same 10 machines quickly.  

However....

In the end I want to integrate pixiecore into my stand up script for our rancher + kubernetes systems.  When you first began to interact with the pixiecore API, what were you using/doing/making?  

:)

PS:
@danderson 10,000 thanks.  You somehow dragged PXE from the turing tar pit into the real world.

**Comment by danderson** [comment]
@hunter I see what you mean, and that matches my needs as well.

For IPMI, I'm not sure Pixiecore is the right place for it, because it would force Pixiecore to become an API server itself (something other components call, to trigger a bootup), whereas right now it's a pure proxy/API translator. The lifecycles of power management and netbooting also don't mesh perfectly - I could set up pixiecore only temporarily to bootstrap install-to-disk, and then shut it down - but I probably want power management/remote console to stay. So, IMO, IPMI-ish things should probably be a separate microservice. That said, if we want to keep things in one place, I'd be happy to pull that microservice into the Pixiecore repository, so that we end up with a complementary set of "bare metal management" microservices.

For cloud-config support, I'm working on a branch right now to enable proxying cloud-config URLs through Pixiecore, which lets the API server dynamically serve cloud configs just like it can currently serve kernels/initrds. Once that is in, I think that should take care of cloud-config support for the most part, what do you think?

@faddat For myself, I'm working on an API server for pixiecore that installs CoreOS with some minimal cloud-config specialization (hostname, network config, maybe a couple of extra daemons). I'll be open-sourcing that as well, once I've got something that actually does anything.

**Comment by faddat** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Sounds good!  I'll keep you up to date on what comes of my efforts
with the pxe booting.  Once I have them nice and stable, I'd like to
submit a PR that will allow pixiecore to give users the single-button
option to boot:

1) Ubuntu
2) Debian
3) Coreos

....and to submit a cloud-config or preseed file.

- -Jake


On 10/1/15 10:14 AM, Dave Anderson wrote:
> @hunter <https://github.com/hunter> I see what you mean, and that 
> matches my needs as well.
> 
> For IPMI, I'm not sure Pixiecore is the right place for it, because
> it would force Pixiecore to become an API server itself (something
> other components call, to trigger a bootup), whereas right now it's
> a pure proxy/API translator. The lifecycles of power management and
> netbooting also don't mesh perfectly - I could set up pixiecore
> only temporarily to bootstrap install-to-disk, and then shut it
> down - but I probably want power management/remote console to stay.
> So, IMO, IPMI-ish things should probably be a separate
> microservice. That said, if we want to keep things in one place,
> I'd be happy to pull that microservice into the Pixiecore
> repository, so that we end up with a complementary set of "bare
> metal management" microservices.
> 
> For cloud-config support, I'm working on a branch right now to
> enable proxying cloud-config URLs through Pixiecore, which lets the
> API server dynamically serve cloud configs just like it can
> currently serve kernels/initrds. Once that is in, I think that
> should take care of cloud-config support for the most part, what do
> you think?
> 
> @faddat <https://github.com/faddat> For myself, I'm working on an
> API server for pixiecore that installs CoreOS with some minimal
> cloud-config specialization (hostname, network config, maybe a
> couple of extra daemons). I'll be open-sourcing that as well, once
> I've got something that actually does anything.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/danderson/pixiecore/issues/4#issuecomment-14460486
0>.
>
-----BEGIN PGP SIGNATURE-----
Comment: GPGTools - https://gpgtools.org

iQIcBAEBCgAGBQJWENwWAAoJEOz3hbjUn3sihswP/0rE4sV01rINAxHaR+pdNsQc
s8Kk53Z864x1fu8r49TMCshaSrfjKmp8KWqfPkPE/DFtHOwhJQbiVe9C5DWNKc93
ZijZ2qr2k47u5hz6s9S+ytfH1HtNC+i6KfWyLYQwf0+0NAaRjStv6gIffzqj2J6i
qewQwMkqLK8h0OQRBBl+sVfVCjnl7laYh1dO5MZqL8qtErbe4iNnFUbH7+/mekve
cR0uBqtOmaPz5oaX3LOwXAgDKl9EgNOCMUMaqYufEIKqxJZw8iSS66EK7Yff7caU
GuHPB7IiyWjqU5sNROBwG5//1aF20t6yqi+Ia0PGRgS/rDrYbPWhsys9S2cK7+B5
Fvan/a238wtDejEmro8Mi+fzAbXbtTMw0al/qKWSAPiN44GXYwjai8EstXiBVPUC
hrTeL2glJ37VEN0jQ6Q9WddYyTtu2GnlC3EjQ3QKthXuKCPEWvgVow14AMgSriRN
hQ8Tccv6crnPsriDDxqNqIM4tCGaEXsqxRX7zDL+22DhnEzQFe9l8S1WRVmX/vdJ
SPvBxCAW//Chh9RZL5Zep3CyHKu89BEmARNSN1uTDaLoRSA9lWOsDJEzg1WSDHux
ybN0IxWuU8Oz4IWGWcXoxaQhopm/eFdk6OnczQxDJ8pDmVs39nlNgNom4Wfy/y80
d/HzvOTaCvkBGQ2uM0OH
=9bc4
-----END PGP SIGNATURE-----

**Comment by steveeJ** [comment]
@hunter and others

I'm curious what solution you've find for this issue. I'm in the very same situation where I'm looking for a flexible solution for spinning up CoreOS host's via (i)PXE. I'd like to include configuration management to supply cloud-configs to the machines. So far I'm playing around with https://github.com/kelseyhightower/coreos-ipxe-server, but it's simply not complete and I wonder if I could share efforts with other interested parties.

**Comment by SpencerBrown** [comment]
@steveeJ [coreos-baremetal](https://github.com/coreos/coreos-baremetal)

**Comment by JonnyBGod** [comment]
I am looking on a way to register new servers on a management service (API) before booting to the final OS.

Flow like:
boot PXELINUX > detect server details (IPMI) > send register call to API > shutdown

IMPI start call > boot final OS ...

Basically I am creating a API+Dashboard to control the cluster very similar to MAAS.

**Comment by faddat** [comment]
@JonnyBGod 

Please get ahold of me on hangouts (faddat@gmail.com)  I'd really like to talk to you about that, because INDEED:  MAAS needs Pixiecore's simplicity and reliability.  I can never get MAAS to work properly.

**Comment by danehans** [comment]
@danderson great work with pixiecore. Have you done any testing with other distros? Do you know what is needed to support other distros?

**Comment by faddat** [comment]
Well, I do.  If you want me to tell you how, ID rather do that "in person"
just send a hangouts message to faddat@gmail.com and I will take you
through the motions.

Isn't pixiecore awesome?
