### ISSUE TITLE
-api flag not working in docker

### ISSUE THREAD

**Issue by xnaveira** [danderson/pixiecore#6]
Hi, I'm running it from the danderson/pixiecore docker in dockerhub and it doesn't take the -api flag??

    flag provided but not defined: -api

**Comment by danderson** [comment]
Woops, I forgot to link the repository to the Docker Hub build. I've linked it now, but the hub builder seems to be broken right now... I'll leave this issue open until I can make Hub build a new version of the binary.

**Comment by xnaveira** [comment]
No worries, I actually had problems to make it build in dockerhub as well
so I build it locally for the moment. Very nice piece of software by the
way, I'm integrating pixiecore with a homegrown installation solution that
my colleague wrote, the idea is that pixiecore will substitute foreman for
the pxe installations in case you are interested:

https://github.com/jhaals/little-foreman/pull/1/files?diff=split

Thanks!

X

**Comment by danderson** [comment]
The docker hub build is (finally) fixed, and has the latest Pixiecore version in it.
